#!/usr/bin/env perl
use strict;
use warnings;

use Term::ReadKey;

my $version="0.41.0";
my $config=$ENV{"HOME"}."/.config/wtf/config.yml";
my $ocolumns=3; #(0-indexed)
my $orows=3; #(0-indexed)

# end of user edits

my ($columns, $rows)=($ocolumns,$orows);

open(my $cf, "<", $config) || die "Can't read $config !! - $!";
while(<$cf>) {
    chomp;
    if ($_=~/left:\s*(\d+)/) {
        if ($1 > $ocolumns) {
            print "found $1 columns is more than $ocolumns.\n";
            $columns=$1;
        }
    } elsif ($_=~/top:\s*(\d+)/) {
        if ($1 > $orows) {
            print "found $1 rows is more than $orows.\n";
            $rows=$1;
        }
    }

}
sub safeRegex($) {
    my $line = shift || die "no line to clean up for regex matching!\n";
    my $regex = $line;
    $regex=~s/([\*\[\]\-\(\)\.\?\/\^\\])/\\$1/g;
    return $regex;
}

my ($wchar, $hchar, $wpixels, $hpixels) = GetTerminalSize();
my $col=sprintf("%d", $wchar/($columns+1));
my $row=sprintf("%d", $hchar/($rows+1));
print "$wchar x $hchar results in: $col x $row\n";

my $columnsLine=("$col, "x($columns+1));
$columnsLine=~s/,\s*$//;
$columnsLine="    columns: [".$columnsLine."]";
my $rowsLine=("$row, "x($rows+1));
$rowsLine=~s/,\s*$//;
$rowsLine="    rows: [".$rowsLine."]";

#print $columnsLine, $rowsLine;

my $error = "";
my $data="";
{
    local @ARGV=($config);
    local $^I = '.lwd'; # <-- turns on inplace editing (d for delete)
    my $cregex = safeRegex("columns: [");
    my $rregex = safeRegex("rows: [");
    while (<>) {
        if (/^[#;]+\s*($cregex|$rregex)/) {
            $data.= "Found '$cregex' or '$rregex' commented out in $config, leaving alone.";
            print;
        } elsif (s/^\s*$rregex.*/$rowsLine/) {
            $data.= "Found '$rregex' in $config, replacing with $rowsLine";
            $error = "found";
            print;
        } elsif (s/^\s*$cregex.*/$columnsLine/) {
            $data.= "Found '$cregex' in $config, replacing with $columnsLine";
            $error = "found";
            print;
        } else {
            print;
        }
    }
}
print (chomp $data) if ($data);
if (defined($error) && $error ne "found") {
    print ("Could not find either regex in $config.");
}

exec($ENV{'HOME'}.'/workspace/wtf-console/wtf_'.$version.'_linux_amd64/wtfutil');

=pod

=head1 (C) Robert Auch  @docsmooth

=head1 Description

=over

wtfutil launcher - dynamically resizes columns and rows for your screen size.
v1.0

This will search out the furthest-left defined column and the lowest row (assuming width 1 and height 1) 
to determine the number of columns and rows, and divide the current screen into equal-sized rows and columns

So if you add a new row or column to your config.yml, you don't need to update the 
"(rows|columns): [x, x, x]" lines.

=back

=head1 Options

No options to this tool.

=head1 Usage

Edit the path to wtfutil on the bottom "exec" line.  Then run it.
